[package]
name = "atc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fundsp = "0.15"
once_cell = "1.18"
serde = { version = "1.0.160", features = ["derive"] }
toml = "0.7.3"
